#!/usr/bin/env python

import os
import sys

size = 0
file_count = 0
folder_count = 0

for folder, _subs, files in os.walk(sys.argv[1], followlinks=False):
    folder_count += 1
    for file in files:
        file_count += 1
        path = os.path.join(folder, file)
        
        try:
            size += os.stat(path).st_size
        except OSError:
            print("Ignoring " + path)
        #end
    #end
#end

print(str(file_count) + " files.")
print(str(folder_count) + " folders.")

if size > 1e9:
    print("%.3f GB" % (float(size)/1e9,))
elif size > 1e6:
    print("%.3f MB" % (float(size)/1e6,))
else:
    print("%.3f KB" % (float(size)/1e3,))